---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-config
  namespace: openshift-config
data:
  bindDN: 'uid=admin,cn=users,dc=example,dc=com'
  ldapUrl: 'ldaps://myldap.server.example.com/cn=users,dc=example,dc=com?uid'