apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - ldap:
        attributes:
          email:
            - mail
          id:
            - dn
          name:
            - displayName
          preferredUsername:
            - uid
        bindDN: '{{ fromConfigMap "openshift-config" "ldap-config" "bindDN" }}'
        bindPassword:
          name: ldap-bind-password
        ca:
          name: ldap-ca-cert
        insecure: false
        url: ""
      mappingMethod: claim
      name: IID
      type: LDAP
