---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - hub-clusters.yaml
  - openshift-clusters.yaml
  - virtualization-host-clusters.yaml
  - workload-clusters.yaml
  - managedclustersetbinding.yaml

replacements:
  - sourceValue: prod-clusters # requires kustomize 5.7.0+
    targets:
      - select:
          kind: Placement
        fieldPaths:
          - spec.clusterSets.0
      - select:
          kind: ManagedClusterSetBinding
        fieldPaths:
          - spec.clusterSet
