---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - hub-clusters.yaml
  - openshift-clusters.yaml
  - virtualization-host-clusters.yaml
  - workload-clusters.yaml
  - managedclustersetbinding.yaml
