---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - acm/
  # - acs/
  # - cluster-logging/
  # - cluster-observability/
  # - compliance/
  # - data-foundation/
  # - file-integrity/
  # - local-storage/
  # - lvm-storage
  # - metallb/
  # - nmstate/
  - openshift-pipelines/
  # - openshift-virtualization/
  # - talm/
