---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: policies

resources:
  - acm-configs/
  - acm-placements/
  # - cluster-configs/
  # - cluster-validations/
  # - operators/
